// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cukfluhqmzkmcqkpxstn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1a2ZsdWhxbXprbWNxa3B4c3RuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MzU0OTAsImV4cCI6MjA3MzQxMTQ5MH0.-TBwWoH27szRH_BIJLN7nOb_oeKP2vRMIBmlC14DrJQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});